// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKN40d08n48yFWMfUM1RA5CxnXkYVwrNk',
    appId: '1:342282499292:web:e342450d33b4612f5b3019',
    messagingSenderId: '342282499292',
    projectId: 'bmcturf-0123',
    authDomain: 'bmcturf-0123.firebaseapp.com',
    storageBucket: 'bmcturf-0123.firebasestorage.app',
    measurementId: 'G-K9ZVPY23W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYQB1cDKK4DR9I8uxxBDB6B_wYGT21F_w',
    appId: '1:342282499292:android:f24ada9501f4ebd25b3019',
    messagingSenderId: '342282499292',
    projectId: 'bmcturf-0123',
    storageBucket: 'bmcturf-0123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEy5-uccbhqylVBSb2e1cvtrtBkszTng',
    appId: '1:342282499292:ios:6ca05bf69500fb675b3019',
    messagingSenderId: '342282499292',
    projectId: 'bmcturf-0123',
    storageBucket: 'bmcturf-0123.firebasestorage.app',
    iosBundleId: 'com.bmcturf.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKN40d08n48yFWMfUM1RA5CxnXkYVwrNk',
    appId: '1:342282499292:web:77391ce2a57deb7f5b3019',
    messagingSenderId: '342282499292',
    projectId: 'bmcturf-0123',
    authDomain: 'bmcturf-0123.firebaseapp.com',
    storageBucket: 'bmcturf-0123.firebasestorage.app',
    measurementId: 'G-KB01FQY56H',
  );

}